### ISSUE TITLE
Launcher not start

### ISSUE THREAD

**Issue by Vitrok86** [BullyWiiPlaza/JMaster-Duel-Bot#11]
![Immagine 2022-10-14 112515](https://user-images.githubusercontent.com/69396500/195812723-80e68714-584a-4ca2-aae8-2d9ad6e0c613.png)

**When I try to start the launcher, it shows this error**
I tried disabling the antivirus but it doesn't work

**Comment by BullyWiiPlaza** [comment]
Hi, I made an update, please re-download it here:
https://github.com/BullyWiiPlaza/JMaster-Duel-Bot/releases

**Comment by Vitrok86** [comment]
Now it works, thanks

Il Ven 14 Ott 2022, 11:37 BullyWiiPlaza ***@***.***> ha
scritto:
