### ISSUE TITLE
无法下载组件

### ISSUE THREAD

**Issue by piaoranjieli** [BullyWiiPlaza/JMaster-Duel-Bot#12]

**Comment by piaoranjieli** [comment]
在安装这个软件之后，点击Launch Application无法下载所有组件，之后软件崩溃
已经安装JAVA

**Comment by piaoranjieli** [comment]
尝试使用VPN也没有作用

**Comment by BullyWiiPlaza** [comment]
Hello, can you try again now and tell me if it works? If you still get an error, please send a screenshot or the exact error message text. Thank you.

---

你好，你现在能不能再试一下，告诉我它是否有效？如果你仍然得到一个错误，请发送一个屏幕截图或确切的错误信息文本。谢谢你。

**Comment by piaoranjieli** [comment]
多次尝试仍然无效，我估计是电脑的网络问题，点击下载后软件崩溃
之后我更换使用手机的网络才成功下载，现在已经可以使用了
很棒的软件，已经完成捐献

**Comment by piaoranjieli** [comment]
是的，而且在我下载完这些组件之后，再重新启动这个软件还仍然需要下载，每次使用都需要拔插手机数据线和网线，这样比较麻烦。
有什么办法可以优化一下吗？或许可以给中国地区加一个服务器？









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BullyWiiPlaza/JMaster-Duel-Bot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月10日(星期四) 下午5:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BullyWiiPlaza/JMaster-Duel-Bot] 无法下载组件 (Issue #12)





 
Thank you. Yes, your network or VPN can be a problem if you come from China.
 
 
谢谢你。是的，如果你来自中国，你的网络或VPN可能是一个问题。

**Comment by BullyWiiPlaza** [comment]
Yes, that might be true for your situation or you can use another VPN. Currently, there's no plan to provide a Chinese server, sorry.

---

是的，你的情况可能是这样的，或者你可以使用另一个VPN。目前，没有计划提供中国的服务器，对不起。
