### ISSUE TITLE
saliva crash 11/17

### ISSUE THREAD

**Issue by PonchoPablo** [BullyWiiPlaza/JMaster-Duel-Bot#14]
Reinstalled it just to be sure it wasn't something on my end. Crashes as soon as the application is opened. Text from crash prompt is below as well as screenshot. 

![Screenshot (33)](https://user-images.githubusercontent.com/118488237/202576127-76ac9933-cd3d-4b3f-a292-ad1e5cdae181.png)

0# iXxy4p2sI83J6rpKWKho in IL2CppDLL
 1# iXxy4p2sI83J6rpKWKho in IL2CppDLL
 2# iXxy4p2sI83J6rpKWKho in IL2CppDLL
 3# UnhandledExceptionFilter in KERNELBASE
 4# memset in ntdll
 5# _C_specific_handler in ntdll
 6# _chkstk in ntdll
 7# RtlRaiseException in ntdll
 8# RtlRaiseException in ntdll
 9# RaiseException in KERNELBASE
10# rwjPeQe0dhBjsa4R0jl6 in IL2CppDLL
11# 0x00007FFFB3635892 in IL2CppDLL
12# iXxy4p2sI83J6rpKWKho in IL2CppDLL
13# WriteZStream in GameAssembly
14# WriteZStream in GameAssembly
15# WriteZStream in GameAssembly
16# WriteZStream in GameAssembly
17# WriteZStream in GameAssembly
18# WriteZStream in GameAssembly
19# WriteZStream in GameAssembly
20# WriteZStream in GameAssembly
21# WriteZStream in GameAssembly
22# WriteZStream in GameAssembly
23# WriteZStream in GameAssembly
24# WriteZStream in GameAssembly
25# WriteZStream in GameAssembly
26# WriteZStream in GameAssembly
27# WriteZStream in GameAssembly
28# WriteZStream in GameAssembly
29# WriteZStream in GameAssembly
30# WriteZStream in GameAssembly
31# WriteZStream in GameAssembly
32# WriteZStream in GameAssembly
33# 0x00007FFFBAD1977C in GameAssembly
34# UnityPalGetTimeZoneDataForID in GameAssembly
35# UnityMain in UnityPlayer
36# UnityMain in UnityPlayer
37# UnityMain in UnityPlayer
38# UnityMain in UnityPlayer
39# UnityMain in UnityPlayer
40# UnityMain in UnityPlayer
41# UnityMain in UnityPlayer
42# UnityMain in UnityPlayer
43# 0x00007FFFBD72E11A in UnityPlayer
44# 0x00007FFFBD72C5DB in UnityPlayer
45# 0x00007FFFBD731762 in UnityPlayer
46# UnityMain in UnityPlayer
47# 0x00007FF7222B11F2 in masterduel
48# BaseThreadInitThunk in KERNEL32
49# RtlUserThreadStart in ntdll

**Comment by BullyWiiPlaza** [comment]
@PonchoPablo Hello, everything is working fine for me. Make sure to restart the bot and game. Also make sure you see `1.3.2` as `Supported Game Version` on the `Settings` tab in the bot and also `Ver: 1.3.2` at the title screen of the game. Let me know if that's the case or not. Thanks.

**Comment by PonchoPablo** [comment]
Everything is working now, thanks my dood
