### ISSUE TITLE
Blocked?

### ISSUE THREAD

**Issue by bvloali** [BullyWiiPlaza/JMaster-Duel-Bot#16]
Whenever the app is opened the game would be closed automatically, blocked?

Edit: after the major game update

**Comment by BullyWiiPlaza** [comment]
Yes, I will fix the bot to be compatible with the new game version later today.

**Comment by bvloali** [comment]
> Yes, I will fix the bot to be compatible with the new game version later today.

Thanks and good luck

**Comment by BullyWiiPlaza** [comment]
It's updated now.
