### ISSUE TITLE
 how can I donate

### ISSUE THREAD

**Issue by 1622208530** [BullyWiiPlaza/JMaster-Duel-Bot#21]
I'd like to know what PVP modes are unlocked by donors and which ones are available, and how can I donate if I need to
![3ECC6EDE07AD437BC9B6F6AC5AB24BB3](https://user-images.githubusercontent.com/132566755/236233737-00d5a947-9cc1-452d-8fdd-65f751a3d947.jpg)
@BullyWiiPlaza

**Comment by 1622208530** [comment]
I don't know about these donor models and what works

**Comment by BullyWiiPlaza** [comment]
Hi, you can donate by going to the `Donator` tab.

The features which work are described in the [`README`](https://github.com/BullyWiiPlaza/JMaster-Duel-Bot/blob/master/README.md), please read all of it.
"Patched" means it's not working anymore basically but I kept it in the program anyway in case people want to play around with them.
