### ISSUE TITLE
Nurse Burn Deck Issue

### ISSUE THREAD

**Issue by FuhKonami** [BullyWiiPlaza/JMaster-Duel-Bot#23]
I let the bot run the Nurse Burn Deck in Ranked, and I found out that it has an issue.

It got stuck trying to use Darklord Ixchel's effect a 2nd time (yes, a 2nd time!) even though that card is hard OTP. It ran out of time and lost the duel by time/surrender type of loss.

But the reason for this is because I added in two more copies of Ixchel to my personal build of Nurse Burn. I had to because Card of Demise and Pot of Duality got Semi Limited some time ago, and the deck's bot wouldn't know how to or to even use any other cards.

Either fix this please by making the bot know to only use one Ixchel per turn and otherwise end its turn or do something else, or by adding in a new card(s) to replace the semi'd cards.

I attached a screenshot of my Nurse Burn deck build for ref.

![image](https://user-images.githubusercontent.com/132245691/236931324-a47ce159-855f-4e3d-83e1-3c1c1ba7d8fc.png)

**Comment by BullyWiiPlaza** [comment]
Thanks but you didn't seem to have read the Duel Bot Tutorial PDF or read my announcements in the Discord server, these sources explain which replacement cards you can use, there are quite a few of them. I will see about adding support for multiple copies of Ixchel as well, I wasn't aware people would try to do this.

**Comment by Fackonami** [comment]
I can’t find the PDF. Where exactly is it?
