### ISSUE TITLE
After the program starts, the system will crash when you click the accept button, and the blue screen code is 0xc00002b4

### ISSUE THREAD

**Issue by ZEXOER** [BullyWiiPlaza/JMaster-Duel-Bot#25]
The jdk version is up to date and no antivirus is running.
Windows11 22H2  22621.1702

**Comment by BullyWiiPlaza** [comment]
Hi, please close all other applications and then try running it again.

**Comment by ZEXOER** [comment]
<img width="365" alt="屏幕截图 2023-07-04 165851" src="https://github.com/BullyWiiPlaza/JMaster-Duel-Bot/assets/102616008/a4aadc9b-defd-4392-b5e0-17a8980d3378">

I reinstalled my system, but it still has a blue screen

**Comment by BullyWiiPlaza** [comment]
As I said, this only occurs if you have certain other processes running so just use it plainly with just the game for example. A fresh installed system will not trigger any issues.
