### ISSUE TITLE
Program only opens in task manager 

### ISSUE THREAD

**Issue by sasels** [BullyWiiPlaza/JMaster-Duel-Bot#29]
Hi the program only opens in task manager and i cant see it anywhere. Also it opens another thing with random 4x4 brackets as name (xxxx_xxxx_xxxx_xxxx). if i close this the program will appear but if i try to start it i get all kinds of errors (timeouts, syntax errors, ...) and need to close it.

**Comment by BullyWiiPlaza** [comment]
Hi, I'm not sure what you mean, can you attach a few screenshots? Maybe you can try to disable your antivirus or firewall if that helps.

**Comment by sasels** [comment]
![md](https://github.com/BullyWiiPlaza/JMaster-Duel-Bot/assets/137488642/af9e2b2c-9902-4f2b-8941-ce5073586c38)
![md2](https://github.com/BullyWiiPlaza/JMaster-Duel-Bot/assets/137488642/db4822a8-ba6f-4c20-ac4c-ddf701df64cd)
![md3](https://github.com/BullyWiiPlaza/JMaster-Duel-Bot/assets/137488642/321651df-9ddd-4320-b597-bc281f4ace69)
i already tried to tun all of it off but nothing changed

**Comment by BullyWiiPlaza** [comment]
Thanks for the screenshots. It seems like your VPN or proxy is misconfigured, you can see that according to the `SSL/TLS connection timeout` or because the JSON parsing failed which should not fail if my website can be accessed normally (the JSON is downloaded from the website and it's valid).

Can you open a CMD window and run the following command?

```
>curl --fail --verbose https://bullywiiplaza.website
*   Trying [64:ff9b::c636:740f]:443...
*   Trying 198.54.116.15:443...
* Connected to bullywiiplaza.website (64:ff9b::c636:740f) port 443 (#0)
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* ALPN: server accepted http/1.1
* using HTTP/1.1
> GET / HTTP/1.1
> Host: bullywiiplaza.website
> User-Agent: curl/8.0.1
> Accept: */*
>
* schannel: remote party requests renegotiation
* schannel: renegotiating SSL/TLS connection
* schannel: SSL/TLS connection renegotiated
* schannel: remote party requests renegotiation
* schannel: renegotiating SSL/TLS connection
* schannel: SSL/TLS connection renegotiated
< HTTP/1.1 200 OK
< keep-alive: timeout=5, max=100
< content-type: text/html
< last-modified: Sat, 23 May 2020 16:11:34 GMT
< accept-ranges: bytes
< content-length: 91
< date: Thu, 22 Jun 2023 08:49:27 GMT
< server: LiteSpeed
< x-turbo-charged-by: LiteSpeed
<
<meta http-equiv="Refresh" content="0; url='https://www.youtube.com/user/BullyWiiPlaza'" />* Connection #0 to host bullywiiplaza.website left intact
```

```
>curl --version
curl 8.0.1 (Windows) libcurl/8.0.1 Schannel WinIDN
Release-Date: 2023-03-20
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets
```

What's the output on your PC?

**Comment by sasels** [comment]
*   Trying 198.54.116.15:443...
* Connected to bullywiiplaza.website (198.54.116.15) port 443 (#0)
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* ALPN: server accepted http/1.1
* using HTTP/1.1
> GET / HTTP/1.1
> Host: bullywiiplaza.website
> User-Agent: curl/8.0.1
> Accept: */*
>
< HTTP/1.1 200 OK
< keep-alive: timeout=5, max=100
< content-type: text/html
< last-modified: Sat, 23 May 2020 16:11:34 GMT
< accept-ranges: bytes
< content-length: 91
< date: Fri, 23 Jun 2023 22:04:10 GMT
< server: LiteSpeed
< x-turbo-charged-by: LiteSpeed
<
<meta http-equiv="Refresh" content="0; url='https://www.youtube.com/user/BullyWiiPlaza'" />* Connection #0 to host bullywiiplaza.website left intact



curl 8.0.1 (Windows) libcurl/8.0.1 Schannel WinIDN
Release-Date: 2023-03-20
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets

**Comment by BullyWiiPlaza** [comment]
That looks fine. I'm wondering what goes wrong. I guess I'll update the launcher to include more transparent feedback regarding errors like with the JSON parsing failure.

**Comment by BullyWiiPlaza** [comment]
@sasels The launcher has now been updated, please try again and send me the more detailed error reports, thank you.
