### ISSUE TITLE
Bot log keeps saying [Donator Authentication Checker]: Generating license key...

### ISSUE THREAD

**Issue by BlueMaxYT** [BullyWiiPlaza/JMaster-Duel-Bot#3]
Basically title. Am I doing something wrong? I'm using the D.D Dynamite deck listed.

**Comment by BullyWiiPlaza** [comment]
Hello, it's normal that the bot log checks the license key regularly. This isn't an issue. Is that all you were concerned about or is there anything that didn't work as well?
