### ISSUE TITLE
Potential bug after closing the application

### ISSUE THREAD

**Issue by zorrodood** [BullyWiiPlaza/JMaster-Duel-Bot#34]
After closing the application there is still something trying to select going first when starting a duel.

Can I stop that somehow?

**Comment by BullyWiiPlaza** [comment]
Hello, it's not a bug. The option is called "Preferred Turn Order" and it's still active even when you close the bot until the game is restarted but you can either
- Disable "Set Preferred Turn Order" in the bot to disable it immediately
- Close the game and re-open the game while the bot is closed to disable all potential influence the bot may have on the game
