### ISSUE TITLE
Unable to lunch Bot

### ISSUE THREAD

**Issue by xJezR** [BullyWiiPlaza/JMaster-Duel-Bot#36]
Hi, I've already use the Bot manytime but I don't know why this time this error occured

![image (1)](https://github.com/BullyWiiPlaza/JMaster-Duel-Bot/assets/145470946/0adc8f6f-8152-433a-82ac-94690c4bf821)
( the french part said " Impossible tho finish the operation because the file contains a virus or unwanted software )

**Comment by BullyWiiPlaza** [comment]
Since you can read, you can also figure out what it means so it should be obvious what to do about it: Allow the file in your antivirus software.
