### ISSUE TITLE
Bot broken by nurse burn Deck

### ISSUE THREAD

**Issue by Chef8989** [BullyWiiPlaza/JMaster-Duel-Bot#37]
i have made made this nurse burn deck from this page 

https://www.masterduelmeta.com/top-decks/wcs-2023-qualifiers-dlv.-max/may-2023/nurse-burn/beefy/WlICD

the Bot is Broken. he do nothing what he should do. mostly use the bot the traps without the monster or Simochi activated, and on the other site the bot uses not the traps if the darklord are not on the field, but simochi

second really stupid action from bot. use first pot of desires so traps like Trap Trick cant be used, although he also has duality in his hand.

and then the bot bricks. no actions like use the other cards in the hand or end round.

also really annoying this the bot not really upgradet since over 2 years. i Used the Bot too on my dark magician/blue eyes deck. he was mostly usefull until he make the stupid decision to make the 2 dragon type monster on the field (dark magigians and the DM dragon for fusions) to make the rank 8 synchro for specialsummon a second dragon from extra deck (he has not used the effect, only Xyz summoned and end turn)

after 2 years of development, you would have thought that the children's diseases would have been lifted and the bot would work with more cards without errors.

edit.

i thought too the bot are usefull in the ritual event with burn damage spells. but he dont use the burn damage spells i picked. only sets the 2 traps in the hand.

i would understand it with the new cards, but not with a deck that has been implemented in the bot since the beginning.

**Comment by BullyWiiPlaza** [comment]
@Chef8989 Hello, when using the Nurse Burn bot deck, please make sure you set the "Duel Bot Type" to "Nurse Burn" in the bot's Settings.

Please read the Duel Bot Tutorial to learn about which cards are supported. You cannot run a Blue-Eyes or Dark Magician deck, what made you think that this works? If you mean solo duels then you're probably using KONAMI's auto duel function (called "Force Auto Dueling" in the bot). For PvP, only my duel bot ("Run Duel Bot") feature will work and the mentioned deck/card restrictions apply. Both duel engines are completely independent from each other. Only KONAMI's somewhat supports all cards and decks. I'm not responsible for the bad decisions it may make, I cannot edit the way it works.

**Comment by Chef8989** [comment]
it is not possible to set the duel bot to nurse burn. it make it automaticly since the last update

**Comment by BullyWiiPlaza** [comment]
> it is not possible to set the duel bot to nurse burn. it make it automaticly since the last update

Please still set it here in case you run into problems:
![image](https://github.com/BullyWiiPlaza/JMaster-Duel-Bot/assets/7620135/1e14f2d3-3389-4792-b0b3-e43bbd32aa3e)
