### ISSUE TITLE
"Server Not Reachable"

### ISSUE THREAD

**Issue by Phrax10k** [BullyWiiPlaza/JMaster-Duel-Bot#38]
I can't open the Duel Bot .exe. I have all of my anti-virus and firewalls turned off and not using a VPN. Please Help.

**Comment by BullyWiiPlaza** [comment]
Hello, this issue is related to your Internet/connection, please switch to mobile or a VPN to see that it works normally. There isn't much I can do from my side, it's working fine for me (without VPN either with my landline WiFi or mobile connection).
