### ISSUE TITLE
Playing "Pot of Duality" or "Banishment of the Darklords" causes a duel loss with a "Connection Failed" message

### ISSUE THREAD

**Issue by Revuin** [BullyWiiPlaza/JMaster-Duel-Bot#39]
Please see video. The message that appeared for a split second after the duel loss was "Connection Failed". 

I am running the Pvp ranked Farming bot using a nurse burn deck. The issue happens only after playing "Pot of Duality" or "Banishment of the Darklords" and it happens consistently. 

Interestingly, it does NOT happen if the opponent has something they can chain. Doesn't matter if they actually chain it. I think the delay of the game waiting for their confirmation prevents the issue from happening.

https://github.com/BullyWiiPlaza/JMaster-Duel-Bot/assets/20654538/e015f928-dabe-45a7-b97e-f48ce0081e8d

**Comment by BullyWiiPlaza** [comment]
Hi, thanks for posting a video. I already saw this issue before being reported by other people but I'm unsure how to resolve it, especially because it doesn't happen for most users of the bot. Generally, this is related to the deck tracker not working so you could check that by toggling the UI to show with the DEL button.

**Comment by Revuin** [comment]
Not seeing anything wrong with the deck tracker. Posting this in case it helps.

I did create the deck using the deck spoofer feature and importing a .ydk file. Maybe that has something to do with it? I'll try creating the deck from scratch instead next.


https://github.com/BullyWiiPlaza/JMaster-Duel-Bot/assets/20654538/b1e13ad6-4e33-4445-bc78-15aaab29221c

**Comment by haha5039** [comment]
In my case, changing (in-game settings) 'Card Position' to 'Manual' fixed it.

**Comment by BullyWiiPlaza** [comment]
> Not seeing anything wrong with the deck tracker. Posting this in case it helps.
> 
> I did create the deck using the deck spoofer feature and importing a .ydk file. Maybe that has something to do with it? I'll try creating the deck from scratch instead next.
> 
>  2023-12-04.22-48-44.mp4

Hi, doing that won't be a problem. Maybe the suggestion by @haha5039 works for you? Let me know. In general, please read and follow the Duel Bot Tutorial PDF, it also explains which settings you should run.

**Comment by Revuin** [comment]
Happy to report that @haha5039 's suggestion is working perfectly. Thank you all.
