### ISSUE TITLE
Bot won't play "Banishment of the Darklords"

### ISSUE THREAD

**Issue by Revuin** [BullyWiiPlaza/JMaster-Duel-Bot#43]
For the Nurse burn deck, the bot no longer plays "Banishment of the Darklords". It's almost like it doesn't know the card.

It used to work before but now it just sets it face-down.

**Comment by BullyWiiPlaza** [comment]
Hi @Revuin, please make sure to set the Duel Bot Type to Nurse Burn:

![image](https://github.com/BullyWiiPlaza/JMaster-Duel-Bot/assets/7620135/9e7e1829-ea87-4a00-a262-ed70cbf1bafb)

Other than that, I'm not sure what would cause that.

**Comment by Revuin** [comment]
Can confirm it is set to Nurse Burn. All other cards are being played correctly too.

**Comment by BullyWiiPlaza** [comment]
Hi, the bot only sets the Banishment spell face-down if the bot wants to play Card of Demise or if the bot knows that it will discard the entire hand at the end of the turn. Can you pay attention if Pot of Duality is played? I didn't update the bot logic in a while so it makes no sense that it would change its behavior like that. For me, it's still working fine as it should.
