### ISSUE TITLE
server connection issue

### ISSUE THREAD

**Issue by crossfire473** [BullyWiiPlaza/JMaster-Duel-Bot#49]
I try and load up the bot but I get a "can't connect to server" message.

I have tried on my lan connection and wireless connection and it does not work.

It also advises to turn off firewalls and antivirus that may block connection which I have tried but still won't work.

It told me to contact if I still have the issue.

**Comment by BullyWiiPlaza** [comment]
Hello, this is mentioned often, please change your WiFi connection to mobile or use a VPN and try again. The server is working fine but your connection to the server is not. Someone in my Discord server wrote:

> I have also experienced it before. There is a issue with your network. You must use an vpn software with ipSec, not a proxy software.
