### ISSUE TITLE
Solo chapter skip Goal to save pack unlock

### ISSUE THREAD

**Issue by randoomdude** [BullyWiiPlaza/JMaster-Duel-Bot#50]
Would you be able to adjust solo clear to not do the goals at the end so that you can save the pack unlock for later if you want?

**Comment by BullyWiiPlaza** [comment]
I don't really understand why you would need this? Currently, it completes all and that's what 99+% of people want. Adding any way of skipping something would be a bit tedious to implement so I would avoid it unless it's extremely useful.

**Comment by BullyWiiPlaza** [comment]
Thanks for the suggestion but due to a lack of usefulness, it won't be implemented for now. You can unlock packs easily by crafting a random SR card from the secret pack. SR dust is fairly cheaply available compared to UR dust.
