### ISSUE TITLE
Doubleclick while using turbo?

### ISSUE THREAD

**Issue by randoomdude** [BullyWiiPlaza/JMaster-Duel-Bot#51]
Turbo is nice but it makes it so you can't double click for confirmation anymore, any way to fix that?

**Comment by BullyWiiPlaza** [comment]
Hello, this is a known issue. You can try to reduce the speed hack speed multiplier to e.g. 2. Also, you can use your laptop's touch screen to bypass the double clicking troubles, if you have a touch screen. A general fix for this option to resolve the double-clicking troubles cannot be done I think.
