### ISSUE TITLE
Feature Request: Tracking of ranked history

### ISSUE THREAD

**Issue by avogatro** [BullyWiiPlaza/JMaster-Duel-Bot#56]
Hi,
I want to track my progress for ranked. 
There is no tool for extracting data from ranked.

I want to extract data like:
Datetime, Coin Flip Result, Player Name, Who play first, Duel Result win/lose, Number of Turn Played, Rank
maybe Deck List of both player.

I am used to other games like online chess, where we could even replay old matches, and correct our own mistakes.

Best Regard

**Comment by BullyWiiPlaza** [comment]
> Hi, I want to track my progress for ranked. There is no tool for extracting data from ranked.
> 
> I want to extract data like: Datetime, Coin Flip Result, Player Name, Who play first, Duel Result win/lose, Number of Turn Played, Rank maybe Deck List of both player.
> 
> I am used to other games like online chess, where we could even replay old matches, and correct our own mistakes.
> 
> Best Regard

Hi, it's interesting you mention this, it has already mostly been done. For instance, the following Master Duel tier list is automated from match statistics which have been extracted/uploaded from Master Duel: https://ygoprodeck.com/master-duel/tier-list
Also, by using the [YGOPRODeck Companion App](https://ygoprodeck.com/master-duel/companion-app), you can track your decks' win ratios, view statistics directly on the website etc.
So far saving/replaying duels/replays is not supported though, that might be significantly harder to achieve.

**Comment by avogatro** [comment]
Hi, thanks for showing me other app. 
The lack of 3rd party statistics is very strange for me, compare to other games like League of legend, World of Warcraft or even World of tanks. Maybe because we can not save replay.

Win rate for going first and win rate for going second should be separated on YGOPRODeck.
I am not interested in Deck general win rate, I am interested in:  if playing the same deck, what is my win rate after I play certain card. That stats can help me optimize my gameplay.

**Comment by BullyWiiPlaza** [comment]
> Hi, thanks for showing me other app. The lack of 3rd party statistics is very strange for me, compare to other games like League of legend, World of Warcraft or even World of tanks. Maybe because we can not save replay.
> 
> Win rate for going first and win rate for going second should be separated on YGOPRODeck. I am not interested in Deck general win rate, I am interested in: if playing the same deck, what is my win rate after I play certain card. That stats can help me optimize my gameplay.

I see but analyzing the content of the duel itself would be related to the replay which is currently not a thing, maybe there's a way to analyze the duel log during the duel with some code, that's at least an idea on how to achieve it more likely in the future.

**Comment by avogatro** [comment]
I wish Konami can enable locally saved replay file as an option. that would make everything easier.

**Comment by BullyWiiPlaza** [comment]
I think this issue has been satisfactorily solved/answered so I'm closing it.
