### ISSUE TITLE
Issues on windows 11 laptop

### ISSUE THREAD

**Issue by randoomdude** [BullyWiiPlaza/JMaster-Duel-Bot#57]
Worked yesterday, wanted to migrate donater + to this new computer but its giving me this error and won't launch app
![image](https://github.com/BullyWiiPlaza/JMaster-Duel-Bot/assets/6027132/d9dd8f3d-ddb3-4757-be22-654658611ee4)

**Comment by tvlasagne** [comment]
likewise

**Comment by BullyWiiPlaza** [comment]
Hello, this issue with the app is now resolved, you can use it again.
