### ISSUE TITLE
.....what this problem?

### ISSUE THREAD

**Issue by black6566516** [BullyWiiPlaza/JMaster-Duel-Bot#58]
<img width="762" alt="{21197A99-50BA-4281-B243-82A0CC1DD58A}" src="https://github.com/BullyWiiPlaza/JMaster-Duel-Bot/assets/104636820/6ba7cd0a-598f-4d07-9ca7-fa79adedd2ca">

**Comment by tvlasagne** [comment]
also have this issue.

**Comment by shiqiemo** [comment]
So did I. I started with java version 19, and it prompted me to update to the latest version, so I updated to version 22, and this happened.Now no matter what version of java I can't use,.The old version will let me update to the new version, and the new version will appear this sentence.And it doesn't give me what is already auto-copied log, so I can't give you the log,for I don't know where the log is.Thanks.

**Comment by BullyWiiPlaza** [comment]
Hello, the issue with the bot is now resolved, you can use it again.

**Note:**  
Updating Java was not necessary, the expired build was the bot app itself which can only be updated by me.

**Comment by shiqiemo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
