### ISSUE TITLE
New Feature - Copy deck from replay

### ISSUE THREAD

**Issue by randoomdude** [BullyWiiPlaza/JMaster-Duel-Bot#60]
For some reason master duel doesn't let you copy some deck lists even if you can view the replay, but I notice Jmaster will pull the decklist during relpays so why not let you copy it as a .YDK so you can add it to your deck collection?
![image](https://github.com/BullyWiiPlaza/JMaster-Duel-Bot/assets/6027132/ae043b70-5da5-4610-a281-f93c73bc390f)

**Comment by randoomdude** [comment]
ideally let you copy deck as .ydk for either player if possible

**Comment by BullyWiiPlaza** [comment]
> ideally let you copy deck as .ydk for either player if possible

Yes, I can add this feature, expect it to be available at some point soon.

**Comment by randoomdude** [comment]
the base feature is working, but if you copy it on turn 0 before cards are played, it will only copy 35/40 and won't copy your 5 hand cards or the extra deck

**Comment by BullyWiiPlaza** [comment]
> the base feature is working, but if you copy it on turn 0 before cards are played, it will only copy 35/40 and won't copy your 5 hand cards or the extra deck

Yes, as you requested, it copies the deck ordering. But I can also grab all cards to make it complete, like how it's shown in the deck tracker.

**Comment by randoomdude** [comment]
thanks, really appreciate the extra features

**Comment by BullyWiiPlaza** [comment]
> thanks, really appreciate the extra features

Hello, the feature is now fully developed with extra deck copying. I will also upload a YouTube video on showing it later but you certainly already know how to use it (since it works the same way).

**Comment by randoomdude** [comment]
The deck copier seems inconsistent with pulling the full list, sometimes it will only copy 1/3 of the cards and not really sure why that is.

![image](https://github.com/user-attachments/assets/25ff6c0b-623c-4543-a722-3381fea4858b)
![image](https://github.com/user-attachments/assets/8e5bab7b-2438-4251-a0b5-f44528e03392)
![image](https://github.com/user-attachments/assets/b0721a6c-8ba8-42ac-8a66-8682c57f8178)
