### ISSUE TITLE
System Error

### ISSUE THREAD

**Issue by yrxva** [BullyWiiPlaza/JMaster-Duel-Bot#65]
A string off error codes come up when letting  JMaster Duel Bot such as a boost_filesystem was not found a couple .dll file like curlpp, libcurl, fmt, etc

**Comment by BullyWiiPlaza** [comment]
Hello, please unpack the whole download as described, then run the EXE. The DLLs are included in the download. Also, you might need to download and install the [x64 C++ Runtime Redistributables 2015 - 2022](https://aka.ms/vs/17/release/vc_redist.x64.exe) if it still doesn't run.
