### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by kidkevin036** [BullyWiiPlaza/JMaster-Duel-Bot#66]
Game crashes when I enter a solo duel.
Video record
https://www.youtube.com/watch?v=xdNgqRtXJnY
(Sorry for using translator)

**Comment by BullyWiiPlaza** [comment]
Hello, does it really only crash if you use Instant Win or also without? The option is working correctly.

**Comment by kidkevin036** [comment]
It crashes without using any functions.
Here is the error log.
[ERROR] 05:51:56.650 [Duel Spy Updater]: 
Lpt6: 2024-06-01 05:51:56.646 (   0.141s) [                ] BotUtilitiesClient.cpp:790    ERR| Failed to find main window handle

**Comment by BullyWiiPlaza** [comment]
Hello, the error you posted is not related to the causes of crashing. Can you try to run the game without opening the bot at all and playing a duel? Does it work or not? If it doesn't work even without using the bot app, please uninstall and reinstall the game fully.

**Comment by kidkevin036** [comment]
The game runs normally when I am not opening the bot.
I can finish the duel and didn't crash.
https://www.youtube.com/watch?v=Za-bmMOiwnk

**Comment by BullyWiiPlaza** [comment]
> The game runs normally when I am not opening the bot. I can finish the duel and didn't crash. https://www.youtube.com/watch?v=Za-bmMOiwnk

Hello, that's interesting. I think it crashes because your game is not in English. This is a general requirement for using the "Run Bot" function. However, I didn't know it would crash like that when you use another language like Chinese. Can you try to change the game to English and see if the bot will work then? Most likely that will help. Thanks. I probably won't provide a fix for using other languages after all.

**Comment by kidkevin036** [comment]
In first video (https://www.youtube.com/watch?v=xdNgqRtXJnY)
I have set my game language to English but it still crashed.
And I just changed my nickname to English but it didn't help.

**Comment by BullyWiiPlaza** [comment]
> In first video (https://www.youtube.com/watch?v=xdNgqRtXJnY) I have set my game language to English but it still crashed. And I just changed my nickname to English but it didn't help.

Oh, I see. It works fine for me. Maybe use an English Steam and an English Windows user name to test? Sorry for the inconvenience.

**Comment by kidkevin036** [comment]
https://www.youtube.com/watch?v=ngaKjDht_WA
I have changed my steam language to English , but it still crashed.
And username is always in English.

**Comment by BullyWiiPlaza** [comment]
Alright, thanks! Can you also try changing your Windows language to English? And testing with no options enabled on the bot? Since it doesn't seem to be the Instant Win option but the bot injects into the game anyway even with nothing enabled. This could still cause the crash.

**Comment by BullyWiiPlaza** [comment]
Recently, I implemented a potential fix for the crashing. If you still have problems, let me know, thanks.
