### ISSUE TITLE
Jmaster bot not working in master duel v. 2.1.1

### ISSUE THREAD

**Issue by Acoah24** [BullyWiiPlaza/JMaster-Duel-Bot#74]
I have runned this jmaster bot in new version of master duel, but its not working,, 

That application is error, and it order us for compliting any java files. 

I hope @BullyWiiPlaza  can update the new jmaster bot. 

Thanks

**Comment by BullyWiiPlaza** [comment]
The bot was already updated yesterday. Please follow the Discord server's #announcements tab for updates.
